# .github/FUNDING.yml
github: ["SamAde1203"]

custom:
  - name: "Buy Me a Coffee – Support My Work"
    url: "https://buymeacoffee.com/samadeyemi"
  - name: "PayPal – Send Support"
    url: "https://paypal.me/SamAdeyemi "
