import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { SimulationResult } from './types';

export async function generatePDFReport(
  elementId: string, 
  protocol: string, 
  result: SimulationResult,
  fileName: string = 'trialforge-report.pdf'
): Promise<void> {
  const element = document.getElementById(elementId);
  if (!element) throw new Error('Element not found');
  
  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,
    logging: false,
    backgroundColor: '#0f172a'
  });
  
  const imgData = canvas.toDataURL('image/png');
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pdfWidth = pdf.internal.pageSize.getWidth();
  const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
  
  pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
  pdf.save(fileName);
}

export function generateTextReport(protocol: string, result: SimulationResult): string {
  return `
TRIALFORGE AI PRO - CLINICAL TRIAL REPORT
==========================================
Generated: ${new Date().toLocaleDateString()}

PROTOCOL ANALYSIS
-----------------
${protocol}

STATISTICAL RESULTS
-------------------
• Statistical Power: ${(result.power * 100).toFixed(1)}% (95% CI: ${(result.powerCI[0] * 100).toFixed(1)}-${(result.powerCI[1] * 100).toFixed(1)}%)
• Required Sample Size: ${result.requiredSample || result.nPerArm * 2} participants
• Average Dropouts: ${result.avgDropouts} (${result.dropoutImpact}% impact)
• Estimated Cost: $${(result.costEstimate / 1000).toFixed(0)}K
• Timeline: ${result.timeline} months

CONSORT FLOW SUMMARY
--------------------
• Assessed: ${result.consort.assessed}
• Randomized: ${result.consort.randomized}  
• Completed: ${result.consort.completed}
• Analyzed: ${result.consort.analyzed}

RECOMMENDATIONS
---------------
${result.recommendations?.map((rec, i) => `${i + 1}. ${rec}`).join('\n') || 'No specific recommendations'}

---
Generated by TrialForge AI Pro - https://trialforge-ai.vercel.app
For research purposes only.
  `.trim();
}