import { TrialParams } from './types';

export function generateProtocolTemplate(trial: TrialParams): string {
  const today = new Date();
  const endDate = new Date(today);
  endDate.setDate(today.getDate() + (trial.weeks * 7));
  
  return `
CLINICAL TRIAL PROTOCOL
=======================

Protocol Title: ${trial.arms[0]?.name || 'Experimental'} vs ${trial.arms[1]?.name || 'Control'} in Target Population
Protocol ID: TF-${Date.now().toString().slice(-6)}
Version: 1.0
Date: ${today.toLocaleDateString()}

1. STUDY DESIGN
---------------
• Design: Randomized, controlled, parallel-group
• Phase: ${trial.n_patients < 100 ? 'II' : 'III'}
• Blinding: Double-blind
• Duration: ${trial.weeks} weeks (${(trial.weeks / 4.345).toFixed(1)} months)

2. PARTICIPANTS
---------------
• Sample Size: ${trial.n_patients} participants
• Allocation: ${Math.floor(trial.n_patients / trial.arms.length)} per arm
• Population: Adults (18-75 years)
• Primary Endpoint: ${trial.endpoint.toUpperCase()}
• Secondary Endpoints: Safety, tolerability, quality of life

3. INTERVENTIONS
----------------
${trial.arms.map((arm, i) => `• Arm ${i + 1}: ${arm.name} (Effect size: ${arm.effect_size.toFixed(2)})`).join('\n')}

4. STATISTICAL CONSIDERATIONS
-----------------------------
• Primary Analysis: Intention-to-treat
• Alpha: 0.05 (two-sided)
• Power: 80% (adjusting for ${(trial.n_patients * 0.15).toFixed(0)} expected dropouts)
• Statistical Test: Mixed models for repeated measures

5. TIMELINE
-----------
• Start: ${today.toLocaleDateString()}
• Enrollment: ${Math.ceil(trial.n_patients / 8)} months
• Follow-up: ${trial.weeks} weeks
• Database Lock: ${endDate.toLocaleDateString()}
• Final Report: ${new Date(endDate.getTime() + 30 * 24 * 60 * 60 * 1000).toLocaleDateString()}

6. RISK ASSESSMENT
------------------
• Statistical Risk: ${trial.n_patients < 100 ? 'Medium' : 'Low'}
• Operational Risk: ${trial.weeks > 26 ? 'Medium' : 'Low'}
• Regulatory Risk: Low (standard design)

---
Generated by TrialForge AI Pro - https://trialforge-ai.vercel.app
This is a template. Consult with biostatistician and regulatory experts.
  `.trim();
}

export function downloadTextFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}